### ISSUE TITLE
Publish on Open VSX?

### ISSUE THREAD

**Issue by mrcasals** [itarato/byesig#10]
hi!

I really like this extension. In my company we're moving to using Gitpod, and this project can't use the default extension registry, but uses the Open VSX one.

Could you publish the extension there, @itarato? Here are the instructions, there's a GitHub Action to help publishing it!

https://github.com/eclipse/openvsx/wiki/Publishing-Extensions#how-to-publish-an-extension

This would be really helpful, thank you!

**Comment by itarato** [comment]
Hi Marc

Appreciate for the details. If I'm not mistaken this might do it: https://open-vsx.org/extension/itarato/byesig - my account is not verified yet though, hope that will happen soon in their issue queue.

**Comment by mrcasals** [comment]
It looks good to me, thank you very much for taking the time! ❤️ 

I think we can close the issue now, I'll do it myself! Thanks again!
